package:
  name: scipoptsuite
  version: 7.0.0

source:
  path: {{ SCIP_DIR }}
  patches:
    - librt-scip.patch
    - librt-papilo.patch
    - libobjscip.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('scipoptsuite', max_pin='x.x') }}

requirements:
  build:
    # Currenlty issue with clang 10.0.0 and "ld: unknown option: -platform_version"
    - {{ compiler('c') }}  # [not osx]
    - {{ compiler('c') }}  <10.0 # [osx]
    - {{ compiler('cxx') }}
    - cmake>=3.15
    - make
  host:
    - zlib
    - readline
    - gmp
    - libgcc-ng  # [linux] Quadmath
    - boost-cpp
    # Disable Papilo for now - tbb-devel

test:
  source_files:
    - scip/examples/Queens
  requires:
    # Currenlty issue with clang 10.0.0 and "ld: unknown option: -platform_version"
    - {{ compiler('c') }}  # [not osx]
    - {{ compiler('c') }}  <10.0 # [osx]
    - {{ compiler('cxx') }}
    - cmake>=3.15
    - make


about:
  home: https://scip.zib.de/
  license: ZIB Academic License
  license_file: COPYING
  summary: Mixed Integer Programming (MIP) solver.
