channels:
  - conda-forge
  - defaults

dependencies:
  # General convenience
  - wget
  - git
  # C++ dev tools
  - make
  - cmake>=3.15
  - clang-tools>=3.4
  - conan
  # Build time Python dependencies
  - python>=3.6
  - pybind11
  - numpy>=1.4
  - xtensor-python
  # Python dev tools
  - ipython
  - pytest
  - pytest-benchmark
  - black
  # Documentation
  - doxygen
  - sphinx>=3.0
  - breathe>=4.15
  - sphinx_rtd_theme
