channels:
  - conda-forge
  - defaults

dependencies:
  - wget
  - git
  - make
  - cmake>=3.15
  - clangdev  # Necessary for tools such as clang-format
  - catch2
  - python>=3.6
  - pybind11
  - ipython
  - pytest
  - black
